# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(634, 685)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 150, 211, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        self.hold_cup1 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.hold_cup1.setObjectName("hold_cup1")
        sizePolicy.setHeightForWidth(self.hold_cup1.sizePolicy().hasHeightForWidth())
        self.hold_cup1.setSizePolicy(sizePolicy)
        self.verticalLayout.addWidget(self.hold_cup1)

        self.hold_cup2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.hold_cup2.setObjectName("hold_cup2")
        sizePolicy.setHeightForWidth(self.hold_cup2.sizePolicy().hasHeightForWidth())
        self.hold_cup2.setSizePolicy(sizePolicy)
        self.verticalLayout.addWidget(self.hold_cup2)

        self.hold_ice1 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.hold_ice1.setObjectName("hold_ice1")
        sizePolicy.setHeightForWidth(self.hold_ice1.sizePolicy().hasHeightForWidth())
        self.hold_ice1.setSizePolicy(sizePolicy)
        self.verticalLayout.addWidget(self.hold_ice1)

        self.hold_ice2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.hold_ice2.setObjectName("hold_ice2")
        
        sizePolicy.setHeightForWidth(self.hold_ice2.sizePolicy().hasHeightForWidth())
        self.hold_ice2.setSizePolicy(sizePolicy)
        self.verticalLayout.addWidget(self.hold_ice2)

        self.go_home = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.go_home.setObjectName("go_home")
        sizePolicy.setHeightForWidth(self.go_home.sizePolicy().hasHeightForWidth())
        self.go_home.setSizePolicy(sizePolicy)
        self.verticalLayout.addWidget(self.go_home)

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=Widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 150, 211, 271))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")


        self.pickup_cof1 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pickup_cof1.setObjectName("pickup_cof1")
        sizePolicy.setHeightForWidth(self.pickup_cof1.sizePolicy().hasHeightForWidth())
        self.pickup_cof1.setSizePolicy(sizePolicy)
        
        self.verticalLayout_2.addWidget(self.pickup_cof1)

        self.pickup_cof2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pickup_cof2.setObjectName("pickup_cof2")
        sizePolicy.setHeightForWidth(self.pickup_cof2.sizePolicy().hasHeightForWidth())
        self.pickup_cof2.setSizePolicy(sizePolicy)
        self.verticalLayout_2.addWidget(self.pickup_cof2)

        self.pickup_bev1 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pickup_bev1.setObjectName("pickup_bev1")
        sizePolicy.setHeightForWidth(self.pickup_bev1.sizePolicy().hasHeightForWidth())
        self.pickup_bev1.setSizePolicy(sizePolicy)
        self.verticalLayout_2.addWidget(self.pickup_bev1)
        
        self.pickup_bev2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pickup_bev2.setObjectName("pickup_bev2")
        sizePolicy.setHeightForWidth(self.pickup_bev2.sizePolicy().hasHeightForWidth())
        self.pickup_bev2.setSizePolicy(sizePolicy)
        self.verticalLayout_2.addWidget(self.pickup_bev2)

        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 430, 211, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.pickup_zone = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pickup_zone.setObjectName("pickup_zone")
        sizePolicy.setHeightForWidth(self.pickup_zone.sizePolicy().hasHeightForWidth())
        self.pickup_zone.setSizePolicy(sizePolicy)
        self.horizontalLayout.addWidget(self.pickup_zone)

        self.zone_num_1 = QtWidgets.QSpinBox(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.zone_num_1.setFont(font)
        self.zone_num_1.setMinimum(1)
        self.zone_num_1.setMaximum(24)
        self.zone_num_1.setObjectName("zone_num_1")
    
        self.horizontalLayout.addWidget(self.zone_num_1)


        self.Title = QtWidgets.QLabel(parent=Widget)
        self.Title.setGeometry(QtCore.QRect(80, 50, 381, 71))
        font_1 = QtGui.QFont()
        font_1.setPointSize(24)
        font_1.setBold(True)
        font_1.setWeight(75)
        self.Title.setFont(font_1)
        self.Title.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Title.setObjectName("Title")

        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Widget)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(300, 500, 211, 71))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.place_zone = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.place_zone.setObjectName("place_zone")
        sizePolicy.setHeightForWidth(self.place_zone.sizePolicy().hasHeightForWidth())
        self.place_zone.setSizePolicy(sizePolicy)
        self.horizontalLayout_2.addWidget(self.place_zone)

        self.zone_num_2 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.zone_num_2.setObjectName("zone_num_2")
        self.zone_num_2.setFont(font)
        self.zone_num_2.setMinimum(1)
        self.zone_num_2.setMaximum(24)
        self.horizontalLayout_2.addWidget(self.zone_num_2)

        self.ExitButton = QtWidgets.QPushButton(Widget)
        self.ExitButton.setObjectName("ExitButton")
        self.ExitButton.setGeometry(QtCore.QRect(490, 60, 111, 51))
        font2 = QtGui.QFont()
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setWeight(75)
        self.ExitButton.setFont(font2)

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Widget)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 560, 211, 121))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.unlock_protective = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.unlock_protective.setObjectName("unlock_protective")
        sizePolicy1 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.unlock_protective.sizePolicy().hasHeightForWidth())
        self.unlock_protective.setSizePolicy(sizePolicy1)

        self.verticalLayout_3.addWidget(self.unlock_protective)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cup_back = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.cup_back.setObjectName("cup_back")
        sizePolicy2 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.cup_back.sizePolicy().hasHeightForWidth())
        self.cup_back.setSizePolicy(sizePolicy2)

        self.horizontalLayout_3.addWidget(self.cup_back)

        self.move_approach = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.move_approach.setObjectName("move_approach")
        sizePolicy2.setHeightForWidth(self.move_approach.sizePolicy().hasHeightForWidth())
        self.move_approach.setSizePolicy(sizePolicy2)

        self.horizontalLayout_3.addWidget(self.move_approach)

        self.move_home = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.move_home.setObjectName("move_home")
        sizePolicy2.setHeightForWidth(self.move_home.sizePolicy().hasHeightForWidth())
        self.move_home.setSizePolicy(sizePolicy2)
        self.move_home.setSizeIncrement(QtCore.QSize(0, 0))

        self.horizontalLayout_3.addWidget(self.move_home)

        self.verticalLayout_3.addLayout(self.horizontalLayout_3)


        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.hold_cup1.setText(_translate("Widget", "1번 컵 채널 빼기"))
        self.hold_cup2.setText(_translate("Widget", "2번 컵 채널 빼기"))
        self.hold_ice1.setText(_translate("Widget", "1번 제빙기 빼기"))
        self.hold_ice2.setText(_translate("Widget", "2번 제빙기 빼기"))
        self.pickup_cof1.setText(_translate("Widget", "1번 커피머신 컵 빼기"))
        self.pickup_cof2.setText(_translate("Widget", "2번 커피머신 컵 빼기"))
        self.pickup_bev1.setText(_translate("Widget", "1번 베버리지 머신 컵 빼기"))
        self.pickup_bev2.setText(_translate("Widget", "2번 베버리지 머신 컵 빼기"))
        self.pickup_zone.setText(_translate("Widget", "픽업 존 컵 잡기"))
        self.go_home.setText(_translate("Widget", "홈 위치로 이동(레일포함)"))
        self.Title.setText(_translate("Widget", "Robot Control GUI"))
        self.place_zone.setText(_translate("Widget", "픽업존 컵 놓기"))
        self.ExitButton.setText(_translate("Widget", "종료하기"))

        self.unlock_protective.setText(_translate("Widget", "프로텍티브 해제"))
        self.move_home.setText(_translate("Widget", "Home"))
        self.move_approach.setText(_translate("Widget", "Approach"))
        self.cup_back.setText(_translate("Widget", "컵DP 복귀"))